"""empty message

Revision ID: 7f5052f4058f
Revises: 
Create Date: 2025-12-19 01:59:36.882276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5052f4058f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_table('despesas',
    sa.Column('pk_despesa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('cpf_responsavel', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['cpf_responsavel'], ['usuarios.cpf'], ),
    sa.PrimaryKeyConstraint('pk_despesa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
