"""Estrutura basica da base de dados

Revision ID: 91cf9d8c26f4
Revises: 
Create Date: 2025-12-21 14:29:30.229879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cf9d8c26f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['cpf'], ['usuarios.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
